# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Typing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenChat
  pod 'AgoraRtm_iOS', '~> 1.2.2'
  # pod "Introspect"
  pod 'ExytePopupView'
end
